###
# creating a new ambulance

POST http://localhost:3000/api/v1/ambulance/create/ HTTP/1.1
Content-Type: application/json

{
    "id": "197714639376036",
    "data": {
        "name": "Hamro ambulance",
        "dName": "Isha pun",
        "pNumber": 9860712345,
        "location": {
            "latitude": 27.685344030241538,
            "longitude": 83.45944723114371
        },
        "owner": "Mutu hospital",
        "status": true,
        "selected": false
    }
}



### 
# get all the ambulances
GET http://localhost:3000/api/v1/ambulance/ HTTP/1.1



### 
# delete all the ambulances
DELETE  http://localhost:3000/api/v1/ambulance/ HTTP/1.1


### 
# track one ambulance
POST  http://localhost:3000/api/v1/ambulance/watch HTTP/1.1
Content-Type: application/json

{
    "id": "19771469376036"
}



###
# updating a ambulance
PATCH http://localhost:3000/api/v1/ambulance/ HTTP/1.1
Content-Type: application/json

{
    "id": "100919117945071530690",
    "data": {
        "name": "Hamro ambulance",
        "dName": "Isha pun",
        "pNumber": 9860712345,
        "location": {
            "latitude": 27.685344030241538,
            "longitude": 83.45944723114371
        },
        "owner": "Saroj regmi",
        "status": true,
        "selected": true
    }
}


###
# update ambulance location
PATCH http://localhost:3000/api/v1/ambulance/location HTTP/1.1
Content-Type: application/json

{
 "id": "197714639376036",  
 "location": {
    "latitude": 27.631432412341324030241538,
    "longitude": 83.4594321413244444444341341
  }
}