###
# creating a new ambulance

POST http://localhost:3000/api/v1/ambulance/create/ HTTP/1.1
Content-Type: application/json

{
    "id": "demoAmbulance",
    "data":  {
       "location":{
        "latitude":27.678342599659278,
        "longitude": 83.46468724836136
      },
      "name": "demoAmbulance",
      "dName": "demoAmbulance",
      "pNumber": 9867100342,
      "vNumber": "BOXYZ24",
      "owner": "Harry Parker",
      "status": true,
      "selected": false
    }
}



### 
# get all the ambulances
GET http://localhost:3000/api/v1/ambulance/ HTTP/1.1



### 
# delete all the ambulances
DELETE  http://localhost:3000/api/v1/ambulance/ HTTP/1.1


### 
# track one ambulance
POST  http://localhost:3000/api/v1/ambulance/watch HTTP/1.1
Content-Type: application/json

{
    "id": "19771469376036"
}



###
# updating a ambulance
PATCH http://localhost:3000/api/v1/ambulance/ HTTP/1.1
Content-Type: application/json

{
    "id": "106838908887260",
    "data":  {
      "location": {
        "latitude": 27.6820234,
        "longitude": 82.4584023
      }, 
      "name": "Kzhsbsjeb",
      "dName": "Skheieebwj",
      "pNumber": 9189281118732,
      "vNumber": "Ksksbsjsb",
      "owner": "sajana regmi",
      "status": true,
      "selected": false
    }
}


###
# update ambulance location
PATCH http://localhost:3000/api/v1/ambulance/location HTTP/1.1
Content-Type: application/json

{
 "id": "197714639376036",  
 "location": {
    "latitude": 27.631432412341324030241538,
    "longitude": 83.4594321413244444444341341
  }
}


 

###
# tracking the demo ambulance
POST http://localhost:3000/api/v1/ambulance/demoAmbulance HTTP/1.1
Content-Type: application/json

{
  "location":{ 
    "latitude":27.678670388060258,
    "longitude": 83.46363045801017
  }
}


### reseting the demo ambulance
PATCH http://localhost:3000/api/v1/ambulance/demoAmbulance/reset HTTP/1.1
