###
#getting all the logs
GET http://localhost:3000/api/v1/log HTTP/1.1
Content-Type: application/json

{
    "id":"1234"
}

###
# adds a new log
POST http://localhost:3000/api/v1/log HTTP/1.1
Content-Type: application/json

{
    "id" : "1234",
    "data" :  
    {
        "name": "Lumbini Ambulance",
        "duration": "5 min",
        "distance": "20 km",
        "date": "8 jun"
    }
}


###
# deletes all the requests
DELETE http://localhost:3000/api/v1/log HTTP/1.1
Content-Type: application/json

{
    "id": "1234"
}