import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    backgroundColor: "white",
    marginTop: 20,
    width: "100%",
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  logo: {},
  name: {
    fontFamily: "poppins-m",
    fontSize: 18,
  },
  vehicleNumber: { marginTop: 10 },
  phoneNumber: {},
  tglBtn: { marginLeft: "auto", marginRight: 30 },
  contents: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  textCont: { marginLeft: 30 },
  editBtn: {
    height: 40,
    width: 220,
    marginRight: "auto",
    marginLeft: "auto",
    textAlign: "center",
    backgroundColor: "#3979FF",
    borderRadius: 15,
    lineHeight: 40,
    color: "#fff",
    marginTop: 30,
    fontFamily: "poppins-m",
    elevation: 5,
  },
  secondaryText: { color: "#6d6d6d", fontFamily: "poppins-r", fontSize: 12 },
});
